// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZZga18IZCAl6NsjUv_t2sBUmm3x8My00',
    appId: '1:628428852056:web:64d4ddd3167978f1eeb32d',
    messagingSenderId: '628428852056',
    projectId: 'emmca-375605',
    authDomain: 'emmca-375605.firebaseapp.com',
    storageBucket: 'emmca-375605.appspot.com',
    measurementId: 'G-DTY876FD5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu6aWJtKc1z1CF0R21Rsg3ZBiKoMHXJuc',
    appId: '1:628428852056:android:f61e4b3a2436fbd4eeb32d',
    messagingSenderId: '628428852056',
    projectId: 'emmca-375605',
    storageBucket: 'emmca-375605.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFtGih3EhJRhvpnZQmL6E7sHvU_fdf7LM',
    appId: '1:628428852056:ios:6e42afab84c054afeeb32d',
    messagingSenderId: '628428852056',
    projectId: 'emmca-375605',
    storageBucket: 'emmca-375605.appspot.com',
    iosClientId:
        '628428852056-tuaa6qm3nm9fhs540ca1e8t95jab3bmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.emmcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFtGih3EhJRhvpnZQmL6E7sHvU_fdf7LM',
    appId: '1:628428852056:ios:6e42afab84c054afeeb32d',
    messagingSenderId: '628428852056',
    projectId: 'emmca-375605',
    storageBucket: 'emmca-375605.appspot.com',
    iosClientId:
        '628428852056-tuaa6qm3nm9fhs540ca1e8t95jab3bmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.emmcare',
  );
}
